# Generated by Django 6.1.1 on 2026-09-11 03:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('nivel', models.CharField(choices=[('imagen', 'Solo imagen / PDF'), ('interactiva', 'Interactiva'), ('premium', 'Premium')], default='interactiva', max_length=20)),
                ('titulo_evento', models.CharField(max_length=150)),
                ('anfitriones', models.CharField(max_length=200)),
                ('fecha_evento', models.DateTimeField()),
                ('lugar_nombre', models.CharField(blank=True, max_length=200)),
                ('lugar_mapa_url', models.URLField(blank=True)),
                ('mensaje_bienvenida', models.TextField(blank=True)),
                ('musica_url', models.URLField(blank=True)),
                ('fecha_limite_rsvp', models.DateField(blank=True, null=True)),
                ('contenido_extra', models.JSONField(blank=True, default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_evento', models.CharField(choices=[('boda', 'Boda'), ('xv', 'XV Años'), ('graduacion', 'Graduación'), ('evento', 'Evento general'), ('fiesta', 'Fiesta')], max_length=20)),
                ('slug_tema', models.SlugField(unique=True)),
                ('soporta_rsvp', models.BooleanField(default=True)),
                ('soporta_musica', models.BooleanField(default=True)),
                ('soporta_galeria', models.BooleanField(default=True)),
                ('vista_previa_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='invitaciones/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('invitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='invitaciones.invitacion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Confirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_invitado', models.CharField(max_length=150)),
                ('asistencia', models.CharField(choices=[('si', 'Sí asistiré'), ('no', 'No podré asistir'), ('tal_vez', 'Tal vez')], max_length=10)),
                ('num_acompanantes', models.PositiveSmallIntegerField(default=0)),
                ('mensaje', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('invitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='invitaciones.invitacion')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddField(
            model_name='invitacion',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones', to='invitaciones.plantilla'),
        ),
    ]
