# Generated by Django 6.1.1 on 2026-09-25 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitaciones", "0002_plantilla_color_tema"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantilla",
            name="soporta_votacion",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="plantilla",
            name="tipo_evento",
            field=models.CharField(
                choices=[
                    ("boda", "Boda"),
                    ("xv", "XV Años"),
                    ("graduacion", "Graduación"),
                    ("evento", "Evento general"),
                    ("fiesta", "Fiesta"),
                    ("baby_shower", "Baby Shower"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Voto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opcion", models.CharField(max_length=40)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "invitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to="invitaciones.invitacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
    ]
