# Generated by Django 6.1.1 on 2026-09-30 08:54

import django.db.models.deletion
import invitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitaciones", "0003_baby_shower_votacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=invitaciones.models._token_pedido,
                        editable=False,
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "cliente",
                    models.CharField(
                        help_text="Para ti: cómo identificas a este cliente (no se publica).",
                        max_length=120,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("imagen", "Solo imagen / PDF"),
                            ("interactiva", "Interactiva"),
                            ("premium", "Premium"),
                        ],
                        default="interactiva",
                        max_length=20,
                    ),
                ),
                ("cancion", models.CharField(blank=True, max_length=300)),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("enviado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "invitacion",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedido",
                        to="invitaciones.invitacion",
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="invitaciones.plantilla",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
    ]
