# Generated by Django 6.1.1 on 2026-09-30 09:26

import invitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitaciones", "0004_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="es_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="token",
            field=models.CharField(
                default=invitaciones.models._token_pedido,
                editable=False,
                max_length=40,
                unique=True,
            ),
        ),
    ]
