"""
Django settings for invitaciones_core project.

ESTE ARCHIVO ES PARA DESARROLLO (tu compu). Producción usa
invitaciones_core/settings_produccion.py, que importa todo lo de aquí y
cambia lo delicado: DEBUG apagado, SECRET_KEY y dominios desde el archivo
.env, cookies solo por HTTPS, etc. Ver DESPLIEGUE.md.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Llave SOLO de desarrollo: ya es pública (está en el historial de git).
# Producción NUNCA la usa: lee DJANGO_SECRET_KEY del archivo .env.
SECRET_KEY = 'django-insecure-x7x$0rwhiqzp^rsio&pp6eqq311+h^%@1&=iucue#e1*3og@hs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Para probar en el celular por HTTPS con un túnel (cloudflared / ngrok): el
# navegador manda Origin https://<algo>.trycloudflare.com y Django rechazaría
# el RSVP (403 CSRF) por no reconocer ese dominio. Solo en desarrollo.
if DEBUG:
    CSRF_TRUSTED_ORIGINS = ['https://*.trycloudflare.com', 'https://*.ngrok-free.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'invitaciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'invitaciones_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'invitaciones_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-mx'

# Hora del centro de México: las fechas que se capturan en el admin se
# interpretan en esta zona. Con 'UTC' el countdown y el archivo de calendario
# (.ics) apuntaban 6 horas antes de la hora real del evento.
TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# A dónde junta "collectstatic" todos los archivos estáticos en el servidor
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media = archivos que suben los usuarios desde el admin (fotos de galería).
# Sin esto Django las guardaba en la raíz del proyecto y su URL daba 404.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Ruta del admin. En producción conviene cambiarla (DJANGO_ADMIN_URL en .env)
# para que los bots que buscan "/admin/" no encuentren la puerta.
ADMIN_URL = 'admin/'


# Protección contra spam en RSVP y votos: (máximo de envíos, ventana en segundos).
# "por_ip" = desde una misma conexión a una misma invitación; "por_invitacion"
# = tope total de una invitación. Con los datos móviles varias personas
# pueden compartir IP, por eso el límite por IP no es de 1 o 2.
LIMITES_RSVP = {'por_ip': (10, 10 * 60), 'por_invitacion': (300, 60 * 60)}
LIMITES_VOTO = {'por_ip': (10, 10 * 60), 'por_invitacion': (300, 60 * 60)}
MAX_ACOMPANANTES = 20

# De qué cabecera se toma la IP del invitado. En tu compu es REMOTE_ADDR;
# detrás del balanceador de un hosting llega en otra (ver settings_produccion).
CABECERA_IP_CLIENTE = 'REMOTE_ADDR'


# Aviso de privacidad (/privacidad/). Los datos del responsable se capturan
# en el .env de producción; si faltan, la página los muestra entre corchetes
# y "manage.py check --deploy" avisa.
MARCA_NOMBRE = os.environ.get('MARCA_NOMBRE', '')
AVISO_RESPONSABLE = os.environ.get('AVISO_RESPONSABLE', '')
AVISO_DOMICILIO = os.environ.get('AVISO_DOMICILIO', '')
AVISO_CORREO = os.environ.get('AVISO_CORREO', '')
AVISO_ACTUALIZADO = '30 de septiembre de 2026'
# Días después del evento en que se borran confirmaciones y votos
# (comando borrar_datos_vencidos). El aviso de privacidad cita este número.
DIAS_RETENCION_DATOS = 90

# Respaldos (comando respaldar_bd)
RESPALDOS_DIR = BASE_DIR / 'respaldos'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
